# Dzień 12 - Pandas: podstawy analizy danych
Pierwsze kroki z biblioteką Pandas: DataFrame, poznawanie struktury danych, wybieranie kolumn i filtrowanie.

In [3]:
import pandas as pd

## Zadanie 1 - Tworzenie pierwszego DataFrame

In [4]:
produkty = {
    "produkt": ["Laptop", "Monitor", "Klawiatura", "Mysz"],
    "kategoria": ["Komputery", "Komputery", "Akcesoria", "Akcesoria"],
    "cena": [3499.99, 899.99, 249.90, 129.99],
    "liczba_sztuk": [2, 5, 8, 10]
}
df = pd.DataFrame(produkty)
df

      produkt  kategoria     cena  liczba_sztuk
0      Laptop  Komputery  3499.99             2
1     Monitor  Komputery   899.99             5
2  Klawiatura  Akcesoria   249.90             8
3        Mysz  Akcesoria   129.99            10

## Zadanie 2 - Podstawowe informacje o DataFrame

In [9]:
df.head()
df.head(2)
df.shape
df.columns
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   produkt       4 non-null      str
 1   kategoria     4 non-null      str
 2   cena          4 non-null      float64
 3   liczba_sztuk  4 non-null      int64
dtypes: float64(1), int64(1), str(2)
memory usage: 260.0 bytes

## Zadanie 3 - Wybieranie kolumn z DataFrame

In [15]:
df["produkt"]
df[["produkt","cena"]]

      produkt     cena
0      Laptop  3499.99
1     Monitor   899.99
2  Klawiatura   249.90
3        Mysz   129.99

## Zadanie 4 - Filtrowanie danych

In [21]:
df["cena"] > 500
df[df["cena"] > 500]
df[df["kategoria"] == "Akcesoria"]
df[df["liczba_sztuk"] >= 5]

      produkt  kategoria    cena  liczba_sztuk
1     Monitor  Komputery  899.99             5
2  Klawiatura  Akcesoria  249.90             8
3        Mysz  Akcesoria  129.99            10