# Dzień 26 - XML i Pandas: eksport danych do CSV

## Zakres
- przygotowanie DataFrame z danych XML
- kontrola typu kolumny 'cena'
- eksport DataFrame do pliku CSV
- sprawdzenie utworzonego pliku

## Zadanie 1 - Przygotowanie DataFrame do eksportu

In [1]:
lista_produktow = [
    {"id": "1", "nazwa": "Laptop", "cena": "3499.99"},
    {"id": "2", "nazwa": "Monitor", "cena": "899.99"},
    {"id": "3", "nazwa": "Klawiatura", "cena": "249.90"}
]

import pandas as pd
df_produkty = pd.DataFrame(lista_produktow)
df_produkty["cena"] = df_produkty["cena"].astype(float)
df_produkty

  id       nazwa     cena
0  1      Laptop  3499.99
1  2     Monitor   899.99
2  3  Klawiatura   249.90

## Zadanie 2 - Eksport DataFrame do pliku CSV

In [2]:
df_produkty.to_csv("data/produkty_z_xml.csv", index = False)

## Zadanie 3 - Sprawdzenie wyeksportowanego pliku CSV

In [3]:
df_kontrola = pd.read_csv("data/produkty_z_xml.csv")
df_kontrola

   id       nazwa     cena
0   1      Laptop  3499.99
1   2     Monitor   899.99
2   3  Klawiatura   249.90