# Dzień 16 - Pandas: merge() i łączenie DataFrame

## Zakres
- powtórka 'groupby()'
- praca z dwoma DataFrame
- łączenie danych za pomocą 'pd.merge()'
- 'left_on' i 'right_on'
- różnica między INNER JOIN i LEFT JOIN
- analiza danych po połączeniu tabel

## Zadanie 1 - Powtórka groupby()

In [4]:
import pandas as pd

produkty = {
    "produkt": ["Laptop", "Monitor", "Klawiatura", "Mysz"],
    "kategoria": ["Komputery", "Komputery", "Akcesoria", "Akcesoria"],
    "cena": [3499.99, 899.99, 249.90, 129.99],
    "liczba_sztuk": [2, 5, 8, 10]
}
df = pd.DataFrame(produkty)
df["wartosc_sprzedazy"] = df["cena"] * df["liczba_sztuk"]

sprzedaz_kategorie = df.groupby("kategoria")["wartosc_sprzedazy"].sum()
sprzedaz_kategorie = sprzedaz_kategorie.reset_index()
sprzedaz_kategorie.sort_values("wartosc_sprzedazy", ascending= False)

   kategoria  wartosc_sprzedazy
1  Komputery           11499.93
0  Akcesoria            3299.10

## Zadanie 2 - Przygotowanie danych do połączenia

In [ ]:
produkty = {
    "id": [1, 2, 3, 4],
    "produkt": ["Laptop", "Monitor", "Klawiatura", "Mysz"],
    "cena": [3499.99, 899.99, 249.90, 129.99]
}

zamowienia = {
    "produkt_id": [1, 2, 1, 4, 3],
    "liczba_sztuk": [2, 5, 3, 10, 4]
}

df_produkty = pd.DataFrame(produkty)
df_zamowienia = pd.DataFrame(zamowienia)
print("PRODUKTY")
display(df_produkty)
print("ZAMÓWIENIA")
display(df_zamowienia)

PRODUKTY

   id     produkt     cena
0   1      Laptop  3499.99
1   2     Monitor   899.99
2   3  Klawiatura   249.90
3   4        Mysz   129.99

ZAMÓWIENIA

   produkt_id  liczba_sztuk
0           1             2
1           2             5
2           1             3
3           4            10
4           3             4

## Zadanie 3 - Łączenie DataFrame za pomocą merge()

In [11]:
pd.merge(
    df_produkty,
    df_zamowienia,
    left_on="id",
    right_on="produkt_id"
)

   id     produkt     cena  produkt_id  liczba_sztuk
0   1      Laptop  3499.99           1             2
1   1      Laptop  3499.99           1             3
2   2     Monitor   899.99           2             5
3   3  Klawiatura   249.90           3             4
4   4        Mysz   129.99           4            10

## Zadanie 4 - Obliczanie wartości sprzedaży po połączeniu danych

In [15]:
df_polaczone = pd.merge(
    df_produkty,
    df_zamowienia,
    left_on="id",
    right_on="produkt_id"
)

df_polaczone["wartosc_sprzedazy"] = df_polaczone["cena"] * df_polaczone["liczba_sztuk"]
df_polaczone

   id     produkt     cena  produkt_id  liczba_sztuk  wartosc_sprzedazy
0   1      Laptop  3499.99           1             2            6999.98
1   1      Laptop  3499.99           1             3           10499.97
2   2     Monitor   899.99           2             5            4499.95
3   3  Klawiatura   249.90           3             4             999.60
4   4        Mysz   129.99           4            10            1299.90

## Zadanie 5 - Łączna wartość sprzedaży według produktu

In [16]:
sprzedaz_produkty = df_polaczone.groupby("produkt")["wartosc_sprzedazy"].sum()
sprzedaz_produkty = sprzedaz_produkty.reset_index()
sprzedaz_produkty.sort_values("wartosc_sprzedazy", ascending = False)

      produkt  wartosc_sprzedazy
1      Laptop           17499.95
2     Monitor            4499.95
3        Mysz            1299.90
0  Klawiatura             999.60

## Zadanie 6 - INNER JOIN vs LEFT JOIN

In [19]:
nowy_produkt = pd.DataFrame({
    "id": [5],
    "produkt": ["Drukarka"],
    "cena": [699.99]
})

df_produkty = pd.concat([df_produkty, nowy_produkt], ignore_index=True)
display(df_produkty)
display(df_zamowienia)

pd.merge(
    df_produkty,
    df_zamowienia,
    left_on="id",
    right_on="produkt_id",
    how = "left"
)

   id     produkt     cena
0   1      Laptop  3499.99
1   2     Monitor   899.99
2   3  Klawiatura   249.90
3   4        Mysz   129.99
4   5    Drukarka   699.99
5   5    Drukarka   699.99
6   5    Drukarka   699.99

   produkt_id  liczba_sztuk
0           1             2
1           2             5
2           1             3
3           4            10
4           3             4

   id     produkt     cena  produkt_id  liczba_sztuk
0   1      Laptop  3499.99         1.0           2.0
1   1      Laptop  3499.99         1.0           3.0
2   2     Monitor   899.99         2.0           5.0
3   3  Klawiatura   249.90         3.0           4.0
4   4        Mysz   129.99         4.0          10.0
5   5    Drukarka   699.99         NaN           NaN
6   5    Drukarka   699.99         NaN           NaN
7   5    Drukarka   699.99         NaN           NaN

## Zadanie 7 - Analiza sprzedaży po połączeniu danych

In [20]:
df_raport = pd.merge (
    df_produkty,
    df_zamowienia,
    left_on = "id",
    right_on = "produkt_id",
    how = "left"
)
sprzedaz_produkty = df_raport.groupby("produkt")["liczba_sztuk"].sum()
sprzedaz_produkty = sprzedaz_produkty.reset_index()
sprzedaz_produkty.sort_values("liczba_sztuk", ascending=False)

      produkt  liczba_sztuk
4        Mysz          10.0
3     Monitor           5.0
2      Laptop           5.0
1  Klawiatura           4.0
0    Drukarka           0.0