# Dzień 13 - Pandas: podstawowa analiza danych
Powtórzenie filtrowania oraz nauka sortowania, podstawowych agregacji i tworzenia nowych kolumn.

In [1]:
import pandas as pd
produkty = {
    "produkt": ["Laptop", "Monitor", "Klawiatura", "Mysz"],
    "kategoria": ["Komputery", "Komputery", "Akcesoria", "Akcesoria"],
    "cena": [3499.99, 899.99, 249.90, 129.99],
    "liczba_sztuk": [2, 5, 8, 10]
}
df = pd.DataFrame(produkty)

## Zadanie 1 - Powtórka podstaw Pandas

In [ ]:
df.head()
df.shape
df[["produkt", "cena"]]
df[df["cena"] > 500]

   produkt  kategoria     cena  liczba_sztuk
0   Laptop  Komputery  3499.99             2
1  Monitor  Komputery   899.99             5

## Zadanie 2 - Sortowanie danych

In [7]:
df.sort_values("cena", ascending=False)

      produkt  kategoria     cena  liczba_sztuk
0      Laptop  Komputery  3499.99             2
1     Monitor  Komputery   899.99             5
2  Klawiatura  Akcesoria   249.90             8
3        Mysz  Akcesoria   129.99            10

## Zadanie 3 - Podstawowe obliczenia

In [12]:
df["cena"].mean()
df["liczba_sztuk"].sum()
df["cena"].max()
df["cena"].min()

np.float64(129.99)

## Zadanie 4 - Obliczanie wartości sprzedaży

In [18]:
df["wartosc_sprzedazy"]=df["cena"] * df["liczba_sztuk"]
df

      produkt  kategoria     cena  liczba_sztuk  wartosc_sprzedazy
0      Laptop  Komputery  3499.99             2            6999.98
1     Monitor  Komputery   899.99             5            4499.95
2  Klawiatura  Akcesoria   249.90             8            1999.20
3        Mysz  Akcesoria   129.99            10            1299.90

## Zadanie 5 - Filtrowanie według wartości sprzedaży

In [19]:
df[df["wartosc_sprzedazy"]> 2000]

   produkt  kategoria     cena  liczba_sztuk  wartosc_sprzedazy
0   Laptop  Komputery  3499.99             2            6999.98
1  Monitor  Komputery   899.99             5            4499.95

## Zadanie 6 - Filtrowanie i sortowanie danych

In [22]:
df[df["wartosc_sprzedazy"] > 1500].sort_values("wartosc_sprzedazy", ascending=False)

      produkt  kategoria     cena  liczba_sztuk  wartosc_sprzedazy
0      Laptop  Komputery  3499.99             2            6999.98
1     Monitor  Komputery   899.99             5            4499.95
2  Klawiatura  Akcesoria   249.90             8            1999.20

## Zadanie 7 - Analiza wartości sprzedaży

In [23]:
df[df["kategoria"] == "Akcesoria"].sort_values("wartosc_sprzedazy", ascending=False)

      produkt  kategoria    cena  liczba_sztuk  wartosc_sprzedazy
2  Klawiatura  Akcesoria  249.90             8             1999.2
3        Mysz  Akcesoria  129.99            10             1299.9

## Zadanie 8 - Produkt z najwyższą wartością sprzedaży

In [26]:
df["wartosc_sprzedazy"].max()
df.sort_values("wartosc_sprzedazy", ascending=False)

      produkt  kategoria     cena  liczba_sztuk  wartosc_sprzedazy
0      Laptop  Komputery  3499.99             2            6999.98
1     Monitor  Komputery   899.99             5            4499.95
2  Klawiatura  Akcesoria   249.90             8            1999.20
3        Mysz  Akcesoria   129.99            10            1299.90