# Dzień 15 - Pandas: groupby() i analiza wyników

## Zakres
- powtórka 'groupby()'
- agregacje '.sum()', '.mean()', '.min()' i '.max'
- 'reset_index()'
- sortowanie wyników grupowania
- filtrowanie zagregowanych danych
- wyciąganie wniosków biznesowych

In [1]:
import pandas as pd

produkty = {
    "produkt": ["Laptop", "Monitor", "Klawiatura", "Mysz"],
    "kategoria": ["Komputery", "Komputery", "Akcesoria", "Akcesoria"],
    "cena": [3499.99, 899.99, 249.90, 129.99],
    "liczba_sztuk": [2, 5, 8, 10]
}

df = pd.DataFrame(produkty)
df["wartosc_sprzedazy"] = df["cena"] * df["liczba_sztuk"]

## Zadanie 1 - Powtórka grupowania danych

In [4]:
df.groupby("kategoria")["liczba_sztuk"].sum()
df.groupby("kategoria")["cena"].mean()
df.groupby("kategoria")["wartosc_sprzedazy"].sum()

kategoria
Akcesoria     3299.10
Komputery    11499.93
Name: wartosc_sprzedazy, dtype: float64

## Zadanie 2 - Minimum i maksimum według kategorii

In [5]:
df.groupby("kategoria")["cena"].max()
df.groupby("kategoria")["cena"].min()

kategoria
Akcesoria    129.99
Komputery    899.99
Name: cena, dtype: float64

## Zadanie 3 - Zamiana wyniku grupowania na DataFrame

In [13]:
sprzedaz_kategorie = df.groupby("kategoria")["wartosc_sprzedazy"].sum()
sprzedaz_kategorie
sprzedaz_kategorie.reset_index()

   kategoria  wartosc_sprzedazy
0  Akcesoria            3299.10
1  Komputery           11499.93

## Zadanie 4 - Sortowanie zagregowanych danych

In [15]:
sprzedaz_kategorie = sprzedaz_kategorie.reset_index()
sprzedaz_kategorie.sort_values("wartosc_sprzedazy", ascending=False)

   kategoria  wartosc_sprzedazy
1  Komputery           11499.93
0  Akcesoria            3299.10

## Zadanie 5 - Filtrowanie zagregowanych danych

In [17]:
sprzedaz_kategorie[sprzedaz_kategorie["wartosc_sprzedazy"] > 5000]

   kategoria  wartosc_sprzedazy
1  Komputery           11499.93

## Zadanie 6 - Analiza sprzedaży według kategorii

In [18]:
sprzedaz_kategorie = df.groupby("kategoria")["wartosc_sprzedazy"].sum()
sprzedaz_kategorie = sprzedaz_kategorie.reset_index()
sprzedaz_kategorie[sprzedaz_kategorie["wartosc_sprzedazy"] > 3000].sort_values("wartosc_sprzedazy", ascending=False)

   kategoria  wartosc_sprzedazy
1  Komputery           11499.93
0  Akcesoria            3299.10

Analiza wykazała, że kategoria Komputery generuje wyższą łączną wartość sprzedaży niż kategoria Akcesoria - 11499,93 zł w porównaniu z 3299,10 zł.